before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ffmpeg
language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.9.2
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx-19mode
notifications:
  email:
    - mbj@seonic.net
